version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    mem_limit: 1g
    restart: always
    depends_on:
      - db
  db:
    image: postgres:16.2-bullseye 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres115
      POSTGRES_DB: biblioteca
    restart: always